name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version number (e.g., 1.5.5)'
        required: true

jobs:
  update-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      actions: write
      issues: write
      deployments: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Update version in files
      run: |
        VERSION=${{ github.event.inputs.version }}
        
        # Update ultra-vehicle-card.js in dist folder
        sed -i "s/setVersion('V[0-9.]*-beta')/setVersion('V$VERSION-beta')/" dist/ultra-vehicle-card.js
        
        # Increment the import version
        IMPORT_VERSION=$(grep -oP "version\.js\?v=\K\d+" dist/ultra-vehicle-card.js)
        NEW_IMPORT_VERSION=$((IMPORT_VERSION + 1))
        sed -i "s/version\.js?v=$IMPORT_VERSION/version.js?v=$NEW_IMPORT_VERSION/" dist/ultra-vehicle-card.js
        
        # Update other files in dist folder
        for file in dist/ultra-vehicle-card-editor.js dist/localize.js; do
          sed -i "s/version\.js?v=$IMPORT_VERSION/version.js?v=$NEW_IMPORT_VERSION/" $file
        done

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Prepare release ${{ github.event.inputs.version }}
        title: Prepare release ${{ github.event.inputs.version }}
        body: |
          This PR updates the version number to ${{ github.event.inputs.version }} and increments the import version.
          Please review and merge this PR before creating the release.
        branch: prepare-release-${{ github.event.inputs.version }}
        delete-branch: true
